# Generated by Django 5.1.4 on 2026-09-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_inspection_revoke_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='revoke_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='撤回原因'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='revoked_by',
            field=models.CharField(blank=True, max_length=64, verbose_name='撤回人'),
        ),
    ]
